name: openEuler Basic Image

on: 
  pull_request:
    # Only trigger job when file in openeuler changed
    paths:
      - 'openeuler'
      - '.github/workflows/basic-image-push.yml'
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - version: 22.03-lts-sp1
            tags: quay.io/openeuler/openeuler:22.03-lts-sp1,quay.io/openeuler/openeuler:latest,quay.io/openeuler/openeuler:22.03

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            openeuler/2*
          key: build-${{ hashFiles('openeuler/*') }}
          restore-keys: |
            build-
      - name: Download openEuler images
        working-directory: openeuler
        run: ./download.sh ${{ matrix.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to QUAY
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./openeuler/${{ matrix.version }}/
          push: true
          tags: ${{ matrix.tags }}
          platforms: linux/amd64,linux/arm64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
