name: OpenStack Kolla Images test

on:
  pull_request:
    paths:
      - 'kolla'
      - '.github/workflows/kolla-image-push.yml'
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        version: [queens, rocky]

    runs-on: ubuntu-18.04

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        working-directory: kolla
        run: ./build.sh ${{matrix.version}}
